export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const SAVE_COURSE_SUCCESS = 'SAVE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_TREE_SUCCESS = 'LOAD_TREE_SUCCESS';
export const SELECT_NODE_SUCCESS = 'SELECT_NODE_SUCCESS';
export const SAVE_NODE_SUCCESS = 'SAVE_NODE_SUCCESS';

export const LOAD_FREQUENCY_SUCCESS = 'LOAD_FREQUENCY_SUCCESS';
